---
- name: Set up ASA Firewall for the first time
  hosts: asa
  connection: network_cli
  gather_facts: no
  vars_files:
    - ./credentials/asa-credentials.yml
    - ./vars/default_vars.yml
  vars:
    erase: false
    cli:
      host:
      username: "{{ ASA_USERNAME }}"
      password: "{{ ASA_PASSWORD }}"
      authorize: yes
      auth_pass: "{{ ASA_PASSWORD }}"

  tasks:

  - name: Add ACLs to firewalls
    asa_acl:
      lines:
        - access-list ACL-ANSIBLE extended permit tcp any any eq 82
      # provider: "{{ cli }}"
    when: not erase

  - name: Remove ACLs from firewalls
    asa_acl:
      lines:
        - no access-list ACL-ANSIBLE extended permit tcp any any eq 82
      # provider: "{{ cli }}"
    when: erase
