---
- name: Set up ASA Firewall for the first time
  hosts: asa
  connection: network_cli
  gather_facts: no
  vars:
    erase: false

  tasks:

  - name: Add ACLs to firewalls
    asa_acl:
      lines:
        - access-list ACL-ANSIBLE extended permit tcp any any eq 82
      match: strict
      replace: block
    when: not erase

  - name: Remove ACLs from firewalls
    asa_acl:
      lines:
        - no access-list ACL-ANSIBLE extended permit tcp any any eq 82
      # provider: "{{ cli }}"
    when: erase
